// Generated by `bun run build:wasm`. This shim keeps TypeScript commands usable
// before the generated package exists in a fresh checkout.
export {
  FinanceDataSeriesIndex,
  GeoFlowIndex,
  GeoJsonIndex,
  GeoPointIndex,
  ScalarFieldIndex,
  VizEngineWasmDensityIndex,
  VizEngineWasmTableIndex,
  initVizEngineWasm,
  // @ts-ignore
} from "./pkg/moritzbrantner_viz_engine_wasm_embedded";
