// Generated by `bun run build:wasm`. This shim keeps TypeScript commands usable
// before the generated package exists in a fresh checkout.
// @ts-ignore
export { VizEngineWasmDensityIndex, initVizEngineWasm } from "./pkg/viz_engine_wasm_embedded";
