// Generated by `bun run build:wasm`. This shim keeps TypeScript commands usable
// before the generated package exists in a fresh checkout.
// @ts-ignore
export {
  FinanceDataSeriesIndex,
  GeoFlowIndex,
  GeoJsonIndex,
  GeoPointIndex,
  ScalarFieldIndex,
  VizEngineWasmDensityIndex,
  initVizEngineWasm,
} from "./pkg/moritzbrantner_viz_engine_wasm_embedded";
