import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageDir = path.join(rootDir, "src", "wasm", "pkg");
const wasmModuleName = "moritzbrantner_viz_engine_wasm";
const wasmPath = path.join(packageDir, `${wasmModuleName}_bg.wasm`);
const embeddedPath = path.join(packageDir, `${wasmModuleName}_embedded.js`);
const embeddedTypesPath = path.join(packageDir, `${wasmModuleName}_embedded.d.ts`);
const wasmBase64 = readFileSync(wasmPath).toString("base64");

writeFileSync(
  embeddedPath,
  [
    `import * as imports from "./${wasmModuleName}_bg.js";`,
    "",
    `const wasmBase64 = "${wasmBase64}";`,
    "let wasmExports = null;",
    "",
    "export const FinanceDataSeriesIndex = imports.FinanceDataSeriesIndex;",
    "export const GeoFlowIndex = imports.GeoFlowIndex;",
    "export const GeoJsonIndex = imports.GeoJsonIndex;",
    "export const GeoPointIndex = imports.GeoPointIndex;",
    "export const ScalarFieldIndex = imports.ScalarFieldIndex;",
    "export const VizEngineWasmDensityIndex = imports.VizEngineWasmDensityIndex;",
    "export const VizEngineWasmTableIndex = imports.VizEngineWasmTableIndex;",
    "",
    "export function initVizEngineWasm() {",
    "  if (wasmExports) {",
    "    return wasmExports;",
    "  }",
    "",
    "  const bytes = decodeBase64(wasmBase64);",
    "  const module = new WebAssembly.Module(bytes);",
    `  const instance = new WebAssembly.Instance(module, { "./${wasmModuleName}_bg.js": imports });`,
    "",
    "  wasmExports = instance.exports;",
    "  imports.__wbg_set_wasm(wasmExports);",
    "  wasmExports.__wbindgen_start?.();",
    "",
    "  return wasmExports;",
    "}",
    "",
    "function decodeBase64(value) {",
    "  if (typeof atob === 'function') {",
    "    const binary = atob(value);",
    "    const bytes = new Uint8Array(binary.length);",
    "",
    "    for (let index = 0; index < binary.length; index += 1) {",
    "      bytes[index] = binary.charCodeAt(index);",
    "    }",
    "",
    "    return bytes;",
    "  }",
    "",
    "  return Uint8Array.from(Buffer.from(value, 'base64'));",
    "}",
    "",
  ].join("\n"),
);

writeFileSync(
  embeddedTypesPath,
  [
    "export class FinanceDataSeriesIndex {",
    "  constructor(input: unknown);",
    "  free(): void;",
    "  getBars(query: unknown): unknown;",
    "  getBounds(): unknown;",
    "  getTypedReturns(query: unknown): unknown;",
    "  getDownsampledBars(query: unknown): unknown;",
    "  getReturns(query: unknown): unknown;",
    "  getRiskSummary(query: unknown): unknown;",
    "}",
    "",
    "export class GeoFlowIndex {",
    "  constructor(flows: unknown);",
    "  free(): void;",
    "  getBounds(): unknown;",
    "  getViewportFlows(query: unknown, options?: unknown): unknown;",
    "}",
    "",
    "export class GeoJsonIndex {",
    "  constructor(featureCollection: unknown);",
    "  free(): void;",
    "  getBounds(): unknown;",
    "  getViewportFeatures(query: unknown, options?: unknown): unknown;",
    "}",
    "",
    "export class GeoPointIndex {",
    "  constructor(points: unknown, options?: unknown);",
    "  free(): void;",
    "  getBounds(): unknown;",
    "  getClusterExpansionZoom(clusterId: string): number;",
    "  getClusterLeaves(clusterId: string, limit?: number, offset?: number): unknown;",
    "  getHeatFeatures(query: unknown, options?: unknown): unknown;",
    "  getPointById(pointId: string): unknown;",
    "  getViewportAggregation(query: unknown): unknown;",
    "  nearestPoint(query: unknown): unknown;",
    "}",
    "",
    "export class ScalarFieldIndex {",
    "  constructor(points: unknown, options?: unknown);",
    "  free(): void;",
    "  createGrid(): unknown;",
    "  getBounds(): unknown;",
    "  getPointCount(): number;",
    "  getValueAtCoordinate(coordinate: unknown): unknown;",
    "  getValueDomain(): unknown;",
    "}",
    "",
    "export class VizEngineWasmDensityIndex {",
    "  constructor(input: unknown);",
    "  static fromArrays(x: Float64Array, y: Float64Array, sourceIndices: Uint32Array, metricKeys: readonly string[], metrics: Float64Array, metricCount: number, ids: readonly string[], labels: readonly string[]): VizEngineWasmDensityIndex;",
    "  free(): void;",
    "  getBinnedSeries(query: unknown): unknown;",
    "  getTypedBinnedSeries(xMin: number, xMax: number, targetBinCount: number, includeEmptyBins: boolean, valueMode: string): unknown;",
    "  getTypedHeatmap(xMin: number, xMax: number, xBinCount: number, yBinCount: number, includeEmptyCells: boolean, yMin: number, yMax: number): unknown;",
    "  getTypedHistogram(bucketCount: number, includeEmptyBuckets: boolean, xMin: number, xMax: number, valueMin: number, valueMax: number): unknown;",
    "  getTypedRollingSeries(xMin: number, xMax: number, windowSize: number, minPeriods: number, alpha: number, statistic: string): unknown;",
    "  getHeatmap(query: unknown): unknown;",
    "  getHistogram(query: unknown): unknown;",
    "  getRollingSeries(query: unknown): unknown;",
    "  getSeriesBounds(): unknown;",
    "  hitTestX(query: unknown): unknown;",
    "}",
    "",
    "export class VizEngineWasmTableIndex {",
    "  constructor();",
    "  addAsciiStringColumn(values: readonly (string | null)[], validity?: Uint8Array): number;",
    "  addBooleanColumn(values: Uint8Array, validity?: Uint8Array): number;",
    "  addNumericColumn(columnType: string, values: Float64Array, validity?: Uint8Array): number;",
    "  free(): void;",
    "  queryBoolean(columnIndex: number, operator: string, value?: boolean, rowOffset?: number, rowLimit?: number): unknown;",
    "  queryNumeric(query: unknown): unknown;",
    "  queryStringFilter(columnIndex: number, operator: string, value?: string, caseSensitive?: boolean, rowOffset?: number, rowLimit?: number): unknown;",
    "  queryStringSearch(columnIndices: readonly number[], query: string, caseSensitive?: boolean, rowOffset?: number, rowLimit?: number): unknown;",
    "  sortBoolean(columnIndex: number, direction: string, nulls: string, rowOffset?: number, rowLimit?: number): unknown;",
    "  sortNumeric(columnIndex: number, direction: string, nulls: string, rowOffset?: number, rowLimit?: number): unknown;",
    "}",
    "",
    "export function initVizEngineWasm(): WebAssembly.Exports;",
    "",
  ].join("\n"),
);
